name: Pull Request

on:
  pull_request:
    branches: ['master']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.10'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
